default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: QuestionAndAnswerApp_development
  host: localhost
  port: 5432
  username: postgres
  password: root1234